# Generated by Django 4.2 on 2024-10-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0004_alter_item_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_image",
            field=models.ImageField(
                default="comingsoon.jpg", upload_to="item_pictures"
            ),
        ),
    ]
